name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7  # v5.2.0
      with:
        dotnet-version: 8.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 #v3.0.0
    - name: Build
      run: dotnet build TownSuite.TwainScanner.sln -c Release
    - name: publish
      run: |
        .\build.ps1
        .\build_zip.ps1 	
    - name: custom nuget package
      run: |
        cd nugetspec
        .\create_nuget.ps1
        
    - name: Archive artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
      with:
        name: win
        path: |
          build\*.zip
          build\*.nupkg
        retention-days: 1
