name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build TownSuite.TwainScanner.sln -c Release
    - name: publish
      run: dotnet publish TownSuite.TwainScanner.sln -c Release -r win-x64 --self-contained true -o publish
    - name: custom nuget package
      run: |
        cd nugetspec
        .\create_nuget.ps1
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: |
          TownSuite.TwainScanner/bin/AnyCPU/Release
          nugetspec/NugetBuild
        retention-days: 1